env:
  global:
  - secure: f1Dkf/AObhtZJf/OtM/NREIZRzVeuw/QXQkV82WrbszKdpLrm1RwfwTAgcUa+JDiE931LJ41W86JWUia3PbS3pLVSL9gSwfBPk+PU6VM7AeYIVuje1V1tXpZoGlf+0RcfGHZA3JzeNSo65QjKl5iUxrT31wnpQpQ9rdG/bXQrUg=
  - secure: Xjc2qZs42LLIk4lRMc/JdFxeN5pmXUTLFd/stohOTX3g1rmRInXXqYpnXW/S15FjShqgtQAvvmnU/SV9QNpfaMhQVgS1ORVTS10gvy3aLPodW5hB9AGCDiQHXD0r9p+73LfNzenvdtmDme9Pp8PdLwb+spSroRbXgJ3tqHpXntM=
  - secure: H5basCAhwXO3SicUX3VClC9KgLzoeJ1unMeYgP6+HHFxSv+81W5AJG8i8xmbziWC+dsO1c2POFbvS2BRkjhPqh9Me94g0FInBoUlVHiP0TlbSBsRv7K5Ke5fm8LHz5Obkeq2BrE6O76m6m2M301MTwZj43LVw8cPtPbXybQ0MoI=
  phpenv:
  - version-name: "5.5.10"

language: php

php:
  - 5.5

install:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f ci/travis/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  # set 777 on necessary directories
  - sudo chmod 777 cache
  - sudo chmod 777 templates_c
  - sudo chmod 777 uploads
  - sudo chmod 777 install
  - sudo chmod 777 mainfile.php
  - sudo chmod 777 cache
  - sudo chmod 777 modules/formulize/cache
  - sudo chmod 777 modules/formulize/temp
  - sudo chmod 777 modules/formulize/upload
  - sudo chmod 777 modules/formulize/templates/screens/default
  - sudo chmod 777 modules/formulize/export
  # make the trust path because the fcgi process cannot
  - sudo mkdir selenium-848d24bb54d726d
  - sudo chmod 777 selenium-848d24bb54d726d
  # add to .ini and restart
  - phpenv config-add ci/travis/php.ini
  - sudo service apache2 restart
  # copy mysql config file to home dir
  - sudo cp ci/travis/.my.cnf ~/.my.cnf

addons:
  sauce_connect: true

before_script:
  - npm install -g se-interpreter
  - mysql -e 'create database formulize;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - se-interpreter ci/travis/interpreter_config.json
  - cat "error.log"
  - curl http://localhost/index.php

after_script:
  - mysqldump -u root formulize > ci/formulize_test_db.sql
  - cat "ci/formulize_test_db.sql"
  - git add ci/formulize_test_db.sql
  - git commit -m "updating test db [skip ci]"
  - git push https://${GITHUB_TOKEN}@github.com/jegelstaff/formulize.git